export const MOCK_CAMERAS = [
  {
    id: 'cam-1',
    name: 'Bosh bino - Kirish turniketi #1',
    location: '1-bino - Markaziy kirish vestibyuli',
    type: 'ENTRANCE',
    streamUrl: 'rtsp://192.168.1.101:554/stream1',
    status: 'ONLINE',
    resolution: '1080p @ 30fps',
  },
  {
    id: 'cam-2',
    name: 'Janubiy korpus - Chiqish turniketi #2',
    location: 'Janubiy bino - Chiqish eshigi',
    type: 'EXIT',
    streamUrl: 'rtsp://192.168.1.102:554/stream1',
    status: 'ONLINE',
    resolution: '1080p @ 30fps',
  },
  {
    id: 'cam-3',
    name: 'Axborot resurs markazi kirishi #3',
    location: 'Kutubxona atriumi, 1-qavat',
    type: 'ENTRANCE',
    streamUrl: 'rtsp://192.168.1.103:554/stream1',
    status: 'ONLINE',
    resolution: '1080p @ 30fps',
  },
];

export const MOCK_STUDENTS = [
  {
    id: 'stud-1',
    studentCode: 'PROF-2026-001',
    firstName: 'Shukurullo',
    lastName: 'Alixonov',
    email: 'shukurullo.alixonov@educontrol.uz',
    department: 'Axborot texnologiyalari kafedrasi',
    grade: 'Dotsent',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'stud-2',
    studentCode: 'PROF-2026-002',
    firstName: 'Kamoliddin',
    lastName: 'Kamalov',
    email: 'kamoliddin.kamalov@educontrol.uz',
    department: 'Dasturiy injiniring kafedrasi',
    grade: 'Katta o‘qituvchi',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'stud-3',
    studentCode: 'PROF-2026-003',
    firstName: 'Azizbek',
    lastName: 'Rahimov',
    email: 'azizbek.rahimov@educontrol.uz',
    department: 'Kiberxavfsizlik kafedrasi',
    grade: 'Kafedra mudiri',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'stud-4',
    studentCode: 'PROF-2026-004',
    firstName: 'Nodira',
    lastName: 'Karimova',
    email: 'nodira.karimova@educontrol.uz',
    department: 'Oliy matematika kafedrasi',
    grade: 'Professor',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'stud-5',
    studentCode: 'PROF-2026-005',
    firstName: 'Dilshod',
    lastName: 'Ergashev',
    email: 'dilshod.ergashev@educontrol.uz',
    department: 'Axborot texnologiyalari kafedrasi',
    grade: 'Assistent',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'stud-6',
    studentCode: 'PROF-2026-006',
    firstName: 'Zilola',
    lastName: 'Yusupova',
    email: 'zilola.yusupova@educontrol.uz',
    department: 'Chet tillari kafedrasi',
    grade: 'Katta o‘qituvchi',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
];

export const MOCK_METRICS = {
  totalStudents: 6,
  activeStudents: 6,
  presentToday: 5,
  onTimeToday: 4,
  lateToday: 1,
  absentToday: 1,
  attendanceRate: 83.3,
  activeCameras: 3,
  totalCameras: 3,
  today: new Date().toISOString().split('T')[0],
  onTimeTeachers: [
    {
      id: 'stud-1',
      studentCode: 'PROF-2026-001',
      firstName: 'Shukurullo',
      lastName: 'Alixonov',
      department: 'Axborot texnologiyalari kafedrasi',
      grade: 'Dotsent',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      checkInTime: new Date(Date.now() - 3600000 * 3.5).toISOString(),
      status: 'PRESENT',
    },
    {
      id: 'stud-2',
      studentCode: 'PROF-2026-002',
      firstName: 'Kamoliddin',
      lastName: 'Kamalov',
      department: 'Dasturiy injiniring kafedrasi',
      grade: 'Katta o‘qituvchi',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      checkInTime: new Date(Date.now() - 3600000 * 3.2).toISOString(),
      status: 'PRESENT',
    },
    {
      id: 'stud-3',
      studentCode: 'PROF-2026-003',
      firstName: 'Azizbek',
      lastName: 'Rahimov',
      department: 'Kiberxavfsizlik kafedrasi',
      grade: 'Kafedra mudiri',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      checkInTime: new Date(Date.now() - 3600000 * 3.8).toISOString(),
      status: 'PRESENT',
    },
    {
      id: 'stud-4',
      studentCode: 'PROF-2026-004',
      firstName: 'Nodira',
      lastName: 'Karimova',
      department: 'Oliy matematika kafedrasi',
      grade: 'Professor',
      photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      checkInTime: new Date(Date.now() - 3600000 * 3.9).toISOString(),
      status: 'PRESENT',
    },
  ],
  lateTeachers: [
    {
      id: 'stud-5',
      studentCode: 'PROF-2026-005',
      firstName: 'Dilshod',
      lastName: 'Ergashev',
      department: 'Axborot texnologiyalari kafedrasi',
      grade: 'Assistent',
      photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      checkInTime: new Date(Date.now() - 3600000 * 2.5).toISOString(),
      status: 'LATE',
      lateMinutes: 18,
    },
  ],
  absentTeachers: [
    {
      id: 'stud-6',
      studentCode: 'PROF-2026-006',
      firstName: 'Zilola',
      lastName: 'Yusupova',
      department: 'Chet tillari kafedrasi',
      grade: 'Katta o‘qituvchi',
      photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80',
      status: 'ABSENT',
    },
  ],
  hourlyData: [
    { hour: '07:00', count: 0 },
    { hour: '08:00', count: 4 },
    { hour: '09:00', count: 1 },
    { hour: '10:00', count: 0 },
    { hour: '11:00', count: 0 },
    { hour: '12:00', count: 0 },
    { hour: '13:00', count: 0 },
    { hour: '14:00', count: 0 },
    { hour: '15:00', count: 0 },
    { hour: '16:00', count: 0 },
    { hour: '17:00', count: 0 },
    { hour: '18:00', count: 0 },
  ],
  departmentList: [
    { department: 'Axborot texnologiyalari kafedrasi', total: 2, present: 2, rate: 100 },
    { department: 'Dasturiy injiniring kafedrasi', total: 1, present: 1, rate: 100 },
    { department: 'Kiberxavfsizlik kafedrasi', total: 1, present: 1, rate: 100 },
    { department: 'Oliy matematika kafedrasi', total: 1, present: 1, rate: 100 },
    { department: 'Chet tillari kafedrasi', total: 1, present: 0, rate: 0 },
  ],
  recentDetections: [
    {
      id: 'det-1',
      studentId: 'stud-1',
      studentName: 'Shukurullo Alixonov',
      cameraName: 'Bosh bino - Kirish turniketi #1',
      type: 'ARRIVAL',
      confidence: 0.98,
      timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    },
    {
      id: 'det-2',
      studentId: 'stud-2',
      studentName: 'Kamoliddin Kamalov',
      cameraName: 'Bosh bino - Kirish turniketi #1',
      type: 'ARRIVAL',
      confidence: 0.96,
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      id: 'det-3',
      studentId: 'stud-5',
      studentName: 'Dilshod Ergashev',
      cameraName: 'Bosh bino - Kirish turniketi #1',
      type: 'ARRIVAL',
      confidence: 0.94,
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    },
  ],
};
